### ISSUE TITLE
deprecated placeholder class

### ISSUE THREAD

**Issue by mrcoffee1026** [Rosewood-Development/PlayerPoints#1]
`[22:44:49] [Server thread/WARN]: [PlaceholderAPI] playerpoints is attempting to register placeholders via a PlaceholderHook class which is no longer supported!`

On startup logs.

**Comment by Esophose** [comment]
Make sure you are using the latest version of PlaceholderAPI and also that you don't have the old playerpoints placeholder expansion installed still. You can delete it from `/plugins/PlaceholderAPI/expansions/Expansion-PlayerPoints` if it's still there. The placeholders are now built into the plugin.

**Comment by mrcoffee1026** [comment]
yeah that was it, deleted the old one and the new one had no issue.  thanks again.
