### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by LuluxClient** [Rosewood-Development/PlayerPoints#14]
Hello I've been trying to connect playerpoints to a db and it doesn't work and I'm getting this error, I'm using the correct ip and password, the correct db name everything.

error: https://pastebin.com/E6EjW6Gc

![image](https://user-images.githubusercontent.com/62576432/123077141-10248880-d41a-11eb-8d35-70fe35be5b6d.png)

**Comment by Esophose** [comment]
The error suggests that a MySQL driver for your server could not be found, even though it's normally bundled with Spigot. I can try putting in a line of code that attempts to load it, but if that also fails then I'm not sure there's going to be much I can do. I'll let you know when I have an update on this.

**Comment by LuluxClient** [comment]
> The error suggests that a MySQL driver for your server could not be found, even though it's normally bundled with Spigot. I can try putting in a line of code that attempts to load it, but if that also fails then I'm not sure there's going to be much I can do. I'll let you know when I have an update on this.

Thanks for the quick answer, do you have a date in mind where it's going to be fixed ?

**Comment by Esophose** [comment]
Try this one.
[PlayerPoints-3.0.4-SNAPSHOT.zip](https://github.com/Rosewood-Development/PlayerPoints/files/6766441/PlayerPoints-3.0.4-SNAPSHOT.zip)

**Comment by LuluxClient** [comment]
Ill try

**Comment by LuluxClient** [comment]
it's fixed
