### ISSUE TITLE
When players join , using /points give by console will only affect for 1 time whether their names contain Chinese or English characters

### ISSUE THREAD

**Issue by SAFEluren** [Rosewood-Development/PlayerPoints#19]
When players join , using /points give by console will only affect for 1 time whether their names contain Chinese or English characters

Chinese characters
![G_LMSN7 XYPPAHCMGNH_ H7](https://user-images.githubusercontent.com/79032826/132121367-2cf772f5-5ebc-4fa2-bff0-3648bf2a5458.jpg)
![%`K37Z8X%5_JI1H(W3~%)R2](https://user-images.githubusercontent.com/79032826/132121371-22117a54-40ef-4ca8-8b1d-357c8c08d64b.jpg)
![~SZK737@1)S}BHD8CXH~0 Y](https://user-images.githubusercontent.com/79032826/132121372-0971dd3b-52bc-4bec-ac51-24a1beb857cc.jpg)
English characters
![GCDNJN ORDTQ06GA~ TDC$D](https://user-images.githubusercontent.com/79032826/132121391-d3fb7df9-8ddd-44e1-a298-d6833fc8a120.jpg)
![}X@AJ7ODK@FRU{8I3 G8~W7](https://user-images.githubusercontent.com/79032826/132121394-6e9c2d83-1fac-4ef8-930b-1cbd4bbc0e5e.jpg)

**Comment by SAFEluren** [comment]
hey

**Comment by Esophose** [comment]
This has been fixed in the latest commits, it just hasn't been released to Spigot yet.

**Comment by SAFEluren** [comment]
thanks you , xD
