### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by WarnDa** [Rosewood-Development/PlayerPoints#21]
Hello,

Sometimes I got issue with the plugin and the mysql connexion fail, so nobody can't connect into the server and it gives this error :
https://pastebin.com/YhQdUtXK

I have to manually connect to the phpmyadmin using the username/password and it fixes the issue the plugin is connected again to the database.

It's the ONLY plugin that get the issue on my 10 plugins that runs on mysql.
(dedicated machine)

**Comment by Esophose** [comment]
This has to do with MySQL 8 and the outdated MySQL driver that's installed on older Spigot versions. MySQL 8 will only work 100% properly on 1.18+ unless you're using some sort of legacy settings for it.

**Comment by SunshroomChan** [comment]
> This has to do with MySQL 8 and the outdated MySQL driver that's installed on older Spigot versions. MySQL 8 will only work 100% properly on 1.18+ unless you're using some sort of legacy settings for it.

Or you have to add code/repo of MySQL-Connector-J 8 and relocate to support all Spigot version instead
