### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ItzRonaldMLG** [Rosewood-Development/PlayerPoints#23]
Any plans for beginning balance? Like when you join, you start with 100 points.
I would like to give points by console, is that possible?
Maybe allow to change the command so it doesnt collide with other plugins? (If this is possible)

**Comment by Esophose** [comment]
A beginning points balance will probably be added in the future. Yes the `/points give` command works in console. The command can't currently be changed but will be able to in the future. You can use the bukkit commands.yml to add a redirect for now.

**Comment by ItzRonaldMLG** [comment]
> A beginning points balance will probably be added in the future. Yes the `/points give` command works in console. The command can't currently be changed but will be able to in the future. You can use the bukkit commands.yml to add a redirect for now.

Nice!
Only the command cant be fixed like that, i ment it like if you have another plugin already using /points commands. The redirect wont work in that case i think.

**Comment by Esophose** [comment]
Forgot to mention but this was added in the v3.2.1 update.
