### ISSUE TITLE
Placeholder leaderboard

### ISSUE THREAD

**Issue by Heriptik** [Rosewood-Development/PlayerPoints#30]
Hi, it's possible add placeholder for leaderboard 
Example : 

"%playerpoints_leader_#1% -> for the top player 1
"%playerpoints_leader_#2% -> for the top player 2
"%playerpoints_leader_#3% -> for the top player 3
"%playerpoints_leader_#4% -> for the top player 4

or 

"%playerpoints_leaderboard% -> for same preview as /points lead

thanks =)

**Comment by Esophose** [comment]
Those already exist https://github.com/Rosewood-Development/PlayerPoints/wiki/PlaceholderAPI-Support
