### ISSUE TITLE
PlayerPoints API

### ISSUE THREAD

**Issue by Thrasilias** [Rosewood-Development/PlayerPoints#6]
hey, i just figured out you took this project over.
is it possible to still use the api of it, gotta need it since im updating my plugin from 2017 wich used PlayerPoints for the dependency

`            public void run() {
                for (Player p : Bukkit.getOnlinePlayers()) {
                    if (playerPoints.getAPI().look(p.getName()) < 1000) {
                        playerPoints.getAPI().give(p.getUniqueId(), 1);
                        (new CustomScoreBoard()).setScoreboard(p);
                    }
                }
            }`

**Comment by Esophose** [comment]
Yeah the new API is fully backwards compatible with the old one. You can find information for the maven repo it's hosted on in the GitHub wiki page. The old methods have all been deprecated in favor of the new async ones, but they still work and will not be removed.

**Comment by Thrasilias** [comment]
gotta compile it first locally right?

**Comment by Esophose** [comment]
No, if you use Gradle or Maven you can just depend on the PlayerPoints jar that way <https://github.com/Rosewood-Development/PlayerPoints/wiki/API-Getting-Started#gradle>
