### ISSUE TITLE
lookAsync SQL error

### ISSUE THREAD

**Issue by divios** [Rosewood-Development/PlayerPoints#9]
Hi! I'm using your api to add support for Mpoints to my plugin. 

When i tried to get the points balance of a player, it returns this sql error https://pastebin.com/83ybpx7h. 

Is really weird since i'm using the same method used on the lookCommand

**Comment by Esophose** [comment]
I don't see PlayerPoints referenced in that stacktrace anywhere, it looks like an SQL error on your side trying to access the mpoints_PlayerPoints table

**Comment by divios** [comment]
From line 14 to 17 is mpoints accesing that table, not mine

**Comment by divios** [comment]
Oh wait my bad, just realized my error, sorry hehe
